### ISSUE TITLE
Support for CFNetwork apps

### ISSUE THREAD

**Issue by va5ja** [matomo-org/device-detector#5377]
Just as a suggestion. The `isMobileApp()` curently doesn't detect apps with user agent strings like "`AppName/AppVerson, CFNetwork/iOSVersion (4xx/5xx), Darwin/11.0.0 (AppName/1.6 CFNetwork/485.13.9 Darwin/11.0.0)`" or "`Google/2.5.1.13455 CFNetwork/609 Darwin/13.0.0`".
So it doesn't detect apps using CFNetwork. I think it shouldn't be that hard to add regex to support these patterns.

**Comment by va5ja** [comment]
Missing support for newer user agents of such type like: SPORT1/4059 CFNetwork/758.4.3 Darwin/15.5.0
So it would be nice to add CFNetwork version 758.4.3 or Darwin version 15.5.0

**Comment by sgiehl** [comment]
`CFNetwork/758.4.3` should now be detected correctly as `iOS 9.3.2`

**Comment by va5ja** [comment]
I think there's a mistake in oss.xml:

```
  user_agent: CFNetwork/758.2.8 Darwin/15.0.0
  os:
    name: iOS
    short_name: IOS
    version: "9.2"
    platform:
-
  user_agent: CFNetwork/758.3.15 Darwin/15.4.0
  os:
    name: iOS
    short_name: IOS
    version: "9.3"
    platform:
-
  user_agent: SPORT1/4059 CFNetwork/758.4.3 Darwin/15.5.0
  os:
    name: iOS
    short_name: IOS
    version: "9.3.2"
    platform:
```

It should be without SPORT1/4059 right?
