### ISSUE TITLE
Google web snippet

### ISSUE THREAD

**Issue by athoune** [matomo-org/device-detector#5418]
The official doc https://developers.google.com/+/web/snippet/?hl=en says that the user agent is `Google (+https://developers.google.com/+/web/snippet/)` but the regex is `Google.*/\+/web/snippet` why not using something more explicit : `Google \(\+https://developers\.google\.com/\+/web/snippet/\)` ?

**Comment by sanchezzzhak** [comment]
current detections.
```
user_agent: Google (+https://developers.google.com/+/web/snippet/)
bot:
  name: Googlebot
  category: Search bot
  url: http://www.google.com/bot.html
  producer:
    name: Google Inc.
    url: http://www.google.com
```

the issue is closed, I don't see the error
