### ISSUE TITLE
AppEngine-Google; (+http://code.google.com/appengine; appid: s~snapchat-proxy) 

### ISSUE THREAD

**Issue by shaeney** [matomo-org/device-detector#5579]
Firstly, I really want to contribute, but am not familiar with Git repos. I know TFS failry well though.

I've seen this user agent, which resolves as Unknown? I've checked against the Device Detector site too

AppEngine-Google; (+http://code.google.com/appengine; appid: s~snapchat-proxy)

**Comment by shaeney** [comment]
Doh! my mistake. 

I am working through a very large set of User Agents out in the wild and got my spreadsheets mixed up.

**Comment by Asg11555** [comment]
AppEngine-Google; (+http://code.google.com/appengine; appid: s~snapchat-proxy)

**Comment by liviuconcioiu** [comment]
@sanchezzzhak can you close this one? It was fixed by https://github.com/matomo-org/device-detector/pull/5841.

**Comment by sanchezzzhak** [comment]
Currently, an uesr-agent is defined as:
```yml
user_agent: 'AppEngine-Google; (+http://code.google.com/appengine; appid: s~snapchat-proxy)'
bot:
  name: Snapchat Proxy
  category: Crawler
  url: https://www.snapchat.com
  producer:
    name: Snapchat Inc.
    url: https://www.snapchat.com
```
