### ISSUE TITLE
Google home

### ISSUE THREAD

**Issue by pierrocknroll** [matomo-org/device-detector#5750]
Hello,

I launched an audio file through my Google Home with his integrated Chromecast, then my user_agent is :
Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.120 Safari/537.36 CrKey/1.32.118652

Your parser returns me that it is a TV but not really :(

Is it possible to differentiate a TV and a device with a Chromecast on it ?
Thanks!

**Comment by sgiehl** [comment]
The UserAgent is currently detected this way:

```
user_agent: Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.120 Safari/537.36 CrKey/1.32.118652
os:
  name: GNU/Linux
  short_name: LIN
  version: ""
  platform: ARM
client:
  type: browser
  name: Chrome
  short_name: CH
  version: 66.0.3359.120
  engine: Blink
  engine_version: ""
device:
  type: tv
  brand: Google
  model: Chromecast
os_family: GNU/Linux
browser_family: Chrome
```

Imho the type `tv` is the most correct here, as the viewing device type is something like a TV in most cases.
