### ISSUE TITLE
Add detect Google pixel 3 xl

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#5887]
[ ] Mozilla/5.0 (Linux; Android 9; Pixel 3 XL Build/PD1A.180716.001) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

**Comment by sgiehl** [comment]
that should already work:
```
user_agent: Mozilla/5.0 (Linux; Android 9; Pixel 3 XL Build/PD1A.180716.001) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36
os:
  name: Android
  short_name: AND
  version: "9"
  platform: ""
client:
  type: browser
  name: Chrome Mobile
  short_name: CM
  version: 67.0.3396.87
  engine: Blink
  engine_version: ""
device:
  type: smartphone
  brand: GO
  model: Pixel 3 XL
os_family: Android
browser_family: Chrome
```
