### ISSUE TITLE
Samsung Browser conflicts with Brand/Model regexes

### ISSUE THREAD

**Issue by liviuconcioiu** [matomo-org/device-detector#5927]
When not using Samsung Browser:
```
  user_agent: Mozilla/5.0 (Linux; Android 6.0; Zun X Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
  os:
    name: Android
    short_name: AND
    version: "6.0"
    platform: ""
  client:
    type: browser
    name: Chrome
    short_name: CH
    version: "70.0.3538.110"
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: V2
    model: Zun X
  os_family: Android
  browser_family: Chrome
```

When using Samsung Browser:
```
  user_agent: Mozilla/5.0 (Linux; Android 6.0; Zun X Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.4 Chrome/56.0.2924.87 Mobile Safari/537.36
  os:
    name: Android
    short_name: AND
    version: "6.0"
    platform: ""
  client:
    type: browser
    name: Samsung Browser
    short_name: SB
    version: "6.4"
    engine: WebKit
    engine_version: "537.36"
  device:
    type: smartphone
    brand: SA
    model: Unknown
  os_family: Android
  browser_family: Unknown
```
