### ISSUE TITLE
Strange Android user agent "MApi" "efte"

### ISSUE THREAD

**Issue by GregOriol** [matomo-org/device-detector#5932]
Hi,

I've come across a strange user-agent:
```
Mozilla/5.0 (Linux; Android 4.4.2; GT-I9502 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 MApi 1.0 (com.dianping.v1 7.0.0 om_sd_360sz GT-I9502; Android 4.4.2) MApi 1.0 (com.dianping.v1 7.0.0 om_sd_360sz GT-I9502; Android 4.4.2) efte/1.0 (efte-for-android)
```
It is currently detected as:
```
  os:
    name: Android
    short_name: AND
    version: "4.4.2"
    platform: ""
  client:
    type: browser
    name: Chrome Mobile
    short_name: CM
    version: "30.0.0.0"
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: SA
    model: GALAXY S4
  os_family: Android
  browser_family: Chrome
```

but I'm not sure it is right:
* first because of "Version/4.0"
* then because it seems like an in-app browser or something?

What do you think?
