### ISSUE TITLE
The brand with name '1' should be listed in the deviceBrands array

### ISSUE THREAD

**Issue by sleptor** [matomo-org/device-detector#5945]
Detector crashes with the error:
`The brand with name '1' should be listed in the deviceBrands array`

on this user agent:

`Mozilla/5.0 (Linux; Android 5.1.1; M631Y Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36`

**Comment by sgiehl** [comment]
I'm not able to reproduce. Getting this result:
```
user_agent: Mozilla/5.0 (Linux; Android 5.1.1; M631Y Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36
os:
  name: Android
  short_name: AND
  version: 5.1.1
  platform: ""
client:
  type: browser
  name: Chrome Mobile
  short_name: CM
  version: 63.0.3239.111
  engine: Blink
  engine_version: ""
device:
  type: smartphone
  brand: Y2
  model: Altitude
os_family: Android
browser_family: Chrome
```

**Comment by sleptor** [comment]
I investigated it deeper and found what's wrong.
For better performance, I use yaml PECL https://www.php.net/manual/en/function.yaml-parse-file.php
I implemented a simple class
```PHP
class PiwikYamlParser implements \DeviceDetector\Yaml\Parser
{
    public function parseFile($file)
    {
        return yaml_parse_file($file);
    }
}
```
fragment how I use it
```PHP
$parser = new DeviceDetector($ua);
$parser->setYamlParser(new PiwikYamlParser());
$parser->parse();
```

So if I comment out `$parser->setYamlParser(...)` it works perfectly. If I use custom yaml parser it throws exception `The brand with name '1' should be listed in the deviceBrands array`

As it turned out yaml PECL treats `Yes` key in mobiles.yaml as boolean. I guess it's according standard https://yaml.org/type/bool.html

**Solution**: please add single quotes around `Yes` it will solve the issue.

```YAML
# Yes
'Yes':
  regex: 'M631Y'
  device: 'smartphone'
  models:
    - regex: 'M631Y'
      model: 'Altitude'
```
