### ISSUE TITLE
Galaxy S9 shows as duplicate in reports with %2B appended

### ISSUE THREAD

**Issue by mattab** [matomo-org/device-detector#5965]
Reported by email: 

>  I have multiple entries for the GALAXY S9.

See screenshot:

![Screenshot from 2019-05-24 18-30-10](https://user-images.githubusercontent.com/466765/58307180-0ce0fc00-7e52-11e9-9dfa-c077ecaf5e84.png)

In the UI it looks like this:

![Screenshot from 2019-05-24 18-31-54](https://user-images.githubusercontent.com/466765/58307248-3a2daa00-7e52-11e9-80ea-b0e59f80c807.png)

**Comment by mimmi20** [comment]
@mattab Could you add the useragents?

**Comment by Findus23** [comment]
I guess one of them is a S9+ and the `+`/`%2B` isn't displayed correctly in the output.

**Comment by sanchezzzhak** [comment]
Samsung Galaxy S9 User-Agent Example:
`Mozilla/5.0 (Linux; Android 8.0.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36`

parse result:
```
os:
  name: Android
  short_name: AND
  version: 8.0.0
  platform: ""
client:
  type: browser
  name: Chrome Mobile
  short_name: CM
  version: 64.0.3282.137
  engine: Blink
  engine_version: ""
device:
  type: smartphone
  brand: SA
  model: GALAXY S9
os_family: Android
browser_family: Chrome
```
Samsung Galaxy S9+ User-Agent Example:
`Mozilla/5.0 (Linux; Android 8.0.0; SM-G965F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Mobile Safari/537.36`

parse result:
```
os:
  name: Android
  short_name: AND
  version: 8.0.0
  platform: ""
client:
  type: browser
  name: Chrome Mobile
  short_name: CM
  version: 65.0.3325.109
  engine: Blink
  engine_version: ""
device:
  type: smartphone
  brand: SA
  model: GALAXY S9+
os_family: Android
browser_family: Chrome
```

I think this issue can be closed
