### ISSUE TITLE
Optimization search

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#5983]
Create basic regular expressions for the browser receiving components
```
User-Agent: Mozilla/<version> (<system-information>) <platform> (<platform-details>) <extensions>
```
<product>
A product identifier
<product-version>
A version number of the product.
<comment>
Zero or more comments containing sub product informations

parse `Mozilla/5.0 (Linux; Android 5.1; A75 Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36`
<product>    - a75

parse `Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; Gaba_A75 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`
<product>   - gaba a75

step 1
find brands by keywords example SAMSUNG, LG, MEIZU etc

step 2
create structure 
When we got the <product> we are looking for a hash structure
```yml
- a75:
   ...
- gaba a75:
    - regexs: ' Gaba_A75'  // optional & is set then check regex
    - brand: SM                // necessarily & check is brand detect by keywords
    - model: Gaba A75     // necessarily
    - device: smartphone  // optional
    // coalition analysis parameters, often some devices have a minimum and maximum OS version
    - builds: [JDQ39, JDQ38]  // optional
    - versions: [4, 7]                // optional
           
```
the optimization has its pros and cons:
 - minimum number of steps to search for a device 
 - current search device min 1, max 539 parse regular( find brand) 1 or more find model
 - new search min 1 max 2 parse regular

a new structure can be built based on tests
I propose to discuss
