### ISSUE TITLE
Ulefone common regular bad result

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#5990]
https://github.com/matomo-org/device-detector/blob/97e6a4e297d2e2159a710a918a7ebf9442b78cf3/regexes/device/mobiles.yml#L9225
Test
```
Mozilla/5.0 Linux; Android 7.0; Ulefone S7 AppleWebKit/537.36 KHTML, like Gecko Chrome/72.0.3626.119 YaBrowser/19.3.4.339.00 Mobile Safari/537.36
```
Result
```
user_agent: Mozilla/5.0 Linux; Android 7.0; Ulefone S7 AppleWebKit/537.36 KHTML, like Gecko Chrome/72.0.3626.119 YaBrowser/19.3.4.339.00 Mobile Safari/537.36
os:
  name: Android
  short_name: AND
  version: "7.0"
  platform: ""
client:
  type: browser
  name: Yandex Browser
  short_name: YA
  version: 19.3.4.339.00
  engine: Blink
  engine_version: ""
device:
  type: smartphone
  brand: UL
  model: S7 AppleWebKit
os_family: Android
browser_family: Unknown
```
model: S7 **AppleWebKit**

Old useragents:
```
Mozilla/5.0 Linux; Android 7.0; Ulefone S8 AppleWebKit/537.36 KHTML, like Gecko Chrome/75.0.3770.143 Mobile Safari/537.36
Mozilla/5.0 Linux; Android 8.1.0; Ulefone_S1_Pro AppleWebKit/537.36 KHTML, like Gecko Chrome/75.0.3770.101 Mobile Safari/537.36
Mozilla/5.0 Linux; Android 8.1.0; Ulefone_Note 7 AppleWebKit/537.36 KHTML, like Gecko Chrome/75.0.3770.101 Mobile Safari/537.36
Mozilla/5.0 Linux; Android 8.1.0; Ulefone_X AppleWebKit/537.36 KHTML, like Gecko Chrome/75.0.3770.143 Mobile Safari/537.36
```
Perhaps we should delete that definition?
