### ISSUE TITLE
Sistrix Optimizer

### ISSUE THREAD

**Issue by jochenwezel** [matomo-org/device-detector#6035]
The Sistrix Optimizer is missing in the bots.yml. This is the User Agent string in different styles:
```
Mozilla/5.0 (compatible; SISTRIX Optimizer; Uptime; +https://www.sistrix.com/faq/uptime)
Mozilla/5.0 (compatible; SISTRIX Optimizer)
```

These lines could be added to bots.yml:
```yml
- regex: 'SISTRIX Optimizer'
  name: 'SISTRIX Optimizer'
  category: 'Analytics SEO Crawler'
  url: 'https://optimizer.sistrix.com'
  producer:
    name: 'SISTRIX GmbH'
    url: 'http://www.sistrix.de'
```

To the same time, the existing Sistrix Crawler entry could be updated to reflect "Analytics SEO Crawler" as category (instead of "Crawler")

```yml
- regex: 'SISTRIX Crawler'
  name: 'SISTRIX Crawler'
  category: 'Analytics SEO Crawler'
  url: 'http://crawler.sistrix.net'
  producer:
    name: 'SISTRIX GmbH'
    url: 'http://www.sistrix.de'
```
