### ISSUE TITLE
Not Detecting OnePlus 7 Pro

### ISSUE THREAD

**Issue by jLynx** [matomo-org/device-detector#6096]
I'm running the latest and it doesn't seem to detect my OnePlus 3

Mozilla/5.0 (Linux; Android 10; GM1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36

GM1913 = OnePlus 7 Pro

**Comment by sanchezzzhak** [comment]
Hi, This user agent is added to the master branch
https://github.com/matomo-org/device-detector/blob/master/regexes/device/mobiles.yml#L8229

Detect  result:
```yml
user_agent: Mozilla/5.0 (Linux; Android 10; GM1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36
os:
  name: Android
  short_name: AND
  version: "10"
  platform: ""
client:
  type: browser
  name: Chrome Mobile
  short_name: CM
  version: 78.0.3904.108
  engine: Blink
  engine_version: ""
device:
  type: smartphone
  brand: 'ON'
  model: 7 Pro
os_family: Android
browser_family: Chrome
```
