### ISSUE TITLE
Does it detect ios phone model ?

### ISSUE THREAD

**Issue by minanagehsalalma** [matomo-org/device-detector#6158]
Like the user agent just contains if the device is ipad or iphone 
[Image](https://user-images.githubusercontent.com/7047791/72226401-cc5bfd00-355e-11ea-9a82-f255a19196cb.png)

**Comment by sanchezzzhak** [comment]
hi, with the user agent, you can't determine which device model is intended for IOS, Apple did this intentionally to protect the user's identity.

Instagram/Facebook this is the only app that provides a device model for IOS

devilish apple((

**Comment by minanagehsalalma** [comment]
> Apple did this intentionally to protect the user's identity.

Really !! Doesn't this Downgrade  the user experience  ! 


> Instagram/Facebook this is the only app that provides a device model for IOS

Can this be caught by an open hotspot while the app checking for internet connection  ?

And if it's really important for protection why didn't google do the same?

**Comment by sanchezzzhak** [comment]
> Can this be caught by an open hotspot while the app checking for internet connection ?

It's already done.  https://github.com/matomo-org/device-detector/blob/master/regexes/device/mobiles.yml#L496
If the user agent contains the data needed to determine the model, then we determine, otherwise it will be Iphone / ipad, etc

Detect result ver. 3.12.3 
```yml
user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E216 [FBAN/FBIOS;FBAV/170.0.0.60.91;FBBV/105964764;FBDV/iPhone10,1;FBMD/iPhone;FBSN/iOS;FBSV/11.3;FBSS/2;FBCR/Sprint;FBID/phone;FBLC/en_US;FBOP/5;FBRV/106631002]'
os:
  name: iOS
  short_name: IOS
  version: "11.3"
  platform: ""
client:
  type: mobile app
  name: Facebook
  version: 170.0.0.60.91
device:
  type: smartphone
  brand: AP
  model: iPhone 8
os_family: iOS
browser_family: Unknown
```

> And if it's really important for protection why didn't google do the same?

I don't know
