### ISSUE TITLE
Add PetalBot

### ISSUE THREAD

**Issue by ingoratsdorf** [matomo-org/device-detector#6464]
Was getting a lot of hits lately by this:
https://aspiegel.com/petalbot

Product name | User-Agent | Full User-Agent
PetalBot(PC) | PetalBot | Mozilla/5.0(compatible;PetalBot;+https://aspiegel.com/petalbot)
PetalBot(mobile) | PetalBot | Mozilla/5.0 (Linux; Android 7.0;)AppleWebKit/537.36 (KHTML, likeGecko)  Mobile Safari/537.36(compatible; PetalBot;+https://aspiegel.com/petalbot)

**Comment by sanchezzzhak** [comment]
@ingoratsdorf Which version of the detector-device are you using?

PetalBot definition added on 10/09/2020  (version 3.13.1+)

```yml
user_agent: 'Mozilla/5.0 (Linux; Android 7.0;)AppleWebKit/537.36 (KHTML, likeGecko)  Mobile Safari/537.36(compatible; PetalBot;+https://aspiegel.com/petalbot)'
bot:
  name: Petal Bot
  category: Crawler
  url: https://aspiegel.com/petalbot
```

```yml
user_agent: Mozilla/5.0(compatible;PetalBot;+https://aspiegel.com/petalbot)
bot:
  name: Petal Bot
  category: Crawler
  url: https://aspiegel.com/petalbot
```
