### ISSUE TITLE
Uncaught TypeError: Return value of DeviceDetector\Parser\Device\AbstractDeviceParser::getShortCode() must be of the type string, int returned

### ISSUE THREAD

**Issue by paladox** [matomo-org/device-detector#6500]
Hi, I'm seeing this

```
[06-Dec-2020 20:10:54 UTC] PHP Fatal error:  Uncaught TypeError: Return value of DeviceDetector\Parser\Device\AbstractDeviceParser::getShortCode() must be of the type string, int returned in /srv/matomo/vendor/matomo/device-detector/Parser/Device/AbstractDeviceParser.php:924
Stack trace:
#0 /srv/matomo/vendor/matomo/device-detector/DeviceDetector.php(491): DeviceDetector\Parser\Device\AbstractDeviceParser::getShortCode('A1')
#1 /srv/matomo/plugins/DevicesDetection/Columns/DeviceBrand.php(63): DeviceDetector\DeviceDetector->getBrand()
#2 /srv/matomo/core/Tracker/Visit.php(499): Piwik\Plugins\DevicesDetection\Columns\DeviceBrand->onNewVisit(Object(Piwik\Tracker\Request), Object(Piwik\Tracker\Visitor), Object(Piwik\Tracker\ActionPageview))
#3 /srv/matomo/core/Tracker/Visit.php(302): Piwik\Tracker\Visit->triggerHookOnDimensions(Array, 'onNewVisit')
#4 /srv/matomo/core/Tracker/Visit.php(209): Piwik\Tracker\Visit->handleNewVisit(NULL)
#5 /srv/matomo/core/Tracker.php(160): Piwik\Tracker\Visit->handle()
```

in the logs when I have

```
[Tracker]
debug = 1
```

in the config.

Running matomo 4.0.4.

Line 924 is:

```
    /**
     * Returns the brand short code for the given name
     *
     * @param string $brand brand name
     *
     * @return string
     *
     * @deprecated since 4.0 - short codes might be removed in next major release
     */
    public static function getShortCode(string $brand): string
    {
        return \array_search($brand, self::$deviceBrands) ?: '';
    }
```

**Comment by paladox** [comment]
I see this is possibly fixed with https://github.com/matomo-org/device-detector/commit/a5f8efa6d0e8bad81832072a1b3ab9edb0b87e71

Could a new release be done?

**Comment by sgiehl** [comment]
Yes. that's already fixed.
I'm planning to do a new release of device detector tomorrow.

**Comment by paladox** [comment]
Thanks!

**Comment by sanchezzzhak** [comment]
@sgiehl before making a version you need a fix

https://github.com/matomo-org/device-detector/blob/c16b93f2a87a2a8f8b3e2feade7b92a49cc766ef/regexes/device/mobiles.yml#L9302

```yml
Mobicel:
  regex: 'Mobicel_(R1)|(?:Matrix|TRENDY PLUS)(?:[);/ ]|$)'
```
check test
```
-
  user_agent: Mozilla/5.0 (Linux; Android 10; PCHM10 Build/QKQ1.200209.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.92 Mobile Safari/537.36 SP-engine/0.0.0 matrixstyle/0 lite baiduboxapp/4.22.0.11 (Baidu; P1 10)
  os:
    name: Android
    version: "10"
    platform: ""
  client:
    type: mobile app
    name: Baidu Box App
    version: 4.22.0.11
  device:
    type: smartphone
    brand: OPPO
    model: A11
  os_family: Android
  browser_family: Unknown
```
