### ISSUE TITLE
Pixel 4a get detected as Pixel 4

### ISSUE THREAD

**Issue by Nekzuris** [matomo-org/device-detector#6502]
https://lx3rzx16x9.codesandbox.io/#Mozilla/5.0%20(Linux;%20Android%2011;%20Pixel%204a)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/86.0.4240.198%20Mobile%20Safari/537.36

**Comment by sanchezzzhak** [comment]
try updating the data according to the instructions in the repository https://github.com/etienne-martin/device-detector-js#how-to-update-to-a-newer-version-of-matomo

If this doesn't work create a issue there  https://github.com/etienne-martin/device-detector-js

We do not support third-party ports 

matomo-org/device-detector
`Google Pixel 4a` added in version ~3.13.1
 (21/09/2020)
```yml
user_agent: Mozilla/5.0 (Linux; Android 11; Pixel 4a) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36
os:
  name: Android
  version: "11"
  platform: ""
client:
  type: browser
  name: Chrome Mobile
  version: 86.0.4240.198
  engine: Blink
  engine_version: ""
device:
  type: smartphone
  brand: Google
  model: Pixel 4a
os_family: Android
browser_family: Chrome
```
