### ISSUE TITLE
Browzar: Invalid client version in browsers.yml

### ISSUE THREAD

**Issue by andre-kornetzky** [matomo-org/device-detector#6531]
The file contains the following entry:

> # Browzar (https://www.browzar.com/)
> - regex: 'Browzar'
>   name: 'Browzar'
>   version: '$1'

The regex entry does not contain a catching group.
Why is the value of a group used in the version field?

Shouldn't the version be '$1' in the output?
But why does the test not throw any error?

**Comment by sgiehl** [comment]
Guess that's a typo. But `$1` will never appear in any result, as it will be replaced even if there is no matching group

**Comment by andre-kornetzky** [comment]
Sounds good. Is there a way to verify this without much effort?
Unfortunately, version 4.0.2 has not yet been deployed on devicedetector.net.

http://devicedetector.net/?ua=Mozilla%2F4.0+(compatible%3B+MSIE+7.0%3B+Windows+NT+10.0%3B+Win64%3B+x64%3B+Anonymisiert+durch+AlMiSoft+Browser-Maulkorb+39663422%3B+Trident%2F7.0%3B+.NET4.0C%3B+.NET4.0E%3B+.NET+CLR+2.0.50727%3B+.NET+CLR+3.0.30729%3B+.NET+CLR+3.5.30729%3B+Tablet+PC+2.0%3B+Browzar)

**Comment by liviuconcioiu** [comment]
> Sounds good. Is there a way to verify this without much effort?

https://devicedetector.lw1.at/

**Comment by sanchezzzhak** [comment]
@andre-kornetzky 

deploy repository locally
```
git clone https://github.com/matomo-org/device-detector.git
cd device-detector
composer update
php misc/test.php "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; Browzar)"
```
result 
```yml
user_agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; Browzar)
os:
  name: Windows
  version: "7"
  platform: x64
client:
  type: browser
  name: Browzar
  version: ""
  engine: Trident
  engine_version: "7.0"
device:
  type: desktop
  brand: ""
  model: ""
os_family: Windows
browser_family: Internet Explorer
```
you can also try, through online services that support composer. example https://phpsandbox.io/
