### ISSUE TITLE
Yahoo Bots not detected

### ISSUE THREAD

**Issue by bjhawk** [matomo-org/device-detector#6735]
The following useragent strings are not being detected as bots. In my own use case, i've seen something like 100,000+ of these in the last few months.

```
YahooMailProxy; https://help.yahoo.com/kb/yahoo-mail-proxy-SLN28749.html

Mozilla/5.0 (compatible; Yahoo Link Preview; https://help.yahoo.com/kb/mail/yahoo-link-preview-SLN23615.html) maild/1619930332-0
```

The second one can be generalized more, the last param in the URL changes, but everything else is the same

```
Mozilla/5.0 (compatible; Yahoo Link Preview; https://help.yahoo.com/kb/mail/yahoo-link-preview-SLN23615.html) maild/\d{10}-0
```

**Comment by sanchezzzhak** [comment]
added as early as 08.05.2016
```
user_agent: Mozilla/5.0 (compatible; Yahoo Link Preview; https://help.yahoo.com/kb/mail/yahoo-link-preview-SLN23615.html) maild/1619930332-0
bot:
  name: Yahoo! Link Preview
  category: Crawler
  url: https://help.yahoo.com/kb/mail/yahoo-link-preview-SLN23615.html
  producer:
    name: Yahoo! Inc.
    url: http://www.yahoo.com
```
check if you are using the latest version 4.2.2
