### ISSUE TITLE
Improvements for DeviceParse new structure (discussion)

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6802]
add the type to the brand definition array
example new structure

```yml
Brand Name:
 regex: 'common regex'
 device: 'smartphone'
 models:
    - device:'feature phone'
      models:
          - regex: ''
            model: 
   -  device:'tablet'
      models:
          - regex: ''
            model:
   # etc.. 
   
   # The current syntax is also left
   - regex: ''
     device: 'phablet'
     model: ''
```
!!! Risks:
this will break a lot of ports, but it will reduce 1400~ lines in the mobiles.yml
