### ISSUE TITLE
Undetected browser

### ISSUE THREAD

**Issue by hracik** [matomo-org/device-detector#6867]
Visit from Facebook app, in-app browser. Is there something to be detected? E.g. Chrome?

`Mozilla/5.0 (Linux; Android 11; RMX1931 Build/RKQ1.200928.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.82 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/331.0.0.15.119;]`

**Comment by sanchezzzhak** [comment]
FBAV/  - indicates the version of facebook app.

the current definitions is work correctly
```yaml
user_agent: 'Mozilla/5.0 (Linux; Android 11; RMX1931 Build/RKQ1.200928.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.82 Mobile Safari/537.36 [FB_IAB/Orca-Android;FBAV/331.0.0.15.119;]'
os:
  name: Android
  version: "11"
  platform: ""
client:
  type: mobile app
  name: Facebook
  version: 331.0.0.15.119
device:
  type: smartphone
  brand: Realme
  model: X2 Pro
os_family: Android
browser_family: Unknown
```
When Facebook opens a link in the app, Facebook opens the browser in its webview.
If you click open in the full browser in this webview, the useragent will already be different.

Instagram, WeChat, Instagram and a bunch of other applications have the same mechanism.
both in Android and iOS.
