### ISSUE TITLE
Bad detection

### ISSUE THREAD

**Issue by usb248** [matomo-org/device-detector#6896]
Hello, i'm in messenger whereas it displays Facebook
![image_6487327](https://user-images.githubusercontent.com/7659927/140471990-0e20b9a9-65a8-477c-9cb0-496c311310c5.JPG)

**Comment by sanchezzzhak** [comment]
current parse result for matomo/device-detector

```yml
user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60 LightSpeed [FBAN/MessengerLiteForiOS;FBAV/334.2.0.46.118;FBBV/324707651;FBDV/iPhone5,4;FBMD/iPhone;FBSN/iOS;F
BSV/10.3.3;FBSS/2;FBCR/;FBID/phone;F'
os:
  name: iOS
  version: 10.3.3
  platform: ""
client:
  type: mobile app
  name: Facebook Messenger Lite
  version: 334.2.0.46.118
device:
  type: smartphone
  brand: Apple
  model: iPhone 5C
os_family: iOS
browser_family: Unknown
```

In this repository, we are working only to improve this package https://github.com/matomo-org/device-detector
