### ISSUE TITLE
Google Search App??

### ISSUE THREAD

**Issue by eduardokraus** [matomo-org/device-detector#7026]
userAgent => Mozilla/5.0 (iPhone; CPU iPhone OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/180.0.400278405 Mobile/15E148 Safari/604.1

### Return:
> **client**
> - [type] => mobile app
> - [name] => Google Search App
>  - [version] => 180.0

**Comment by sanchezzzhak** [comment]
what is the QA?


last result
```
user_agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/180.0.400278405 Mobile/15E148 Safari/604.1
os:
  name: iOS
  version: "14.7"
  platform: ""
client:
  type: mobile app
  name: Google Search App
  version: 180.0.400278405
device:
  type: smartphone
  brand: Apple
  model: iPhone
os_family: iOS
browser_family: Unknown
```
