### ISSUE TITLE
Improvements to the ClientHints for the xmlhttprequest header

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#7039]
Since we have taken the first step to client Hints, I suggest step on to the second

I suggest discussing the format

```yml
# NM = name app
# CT = category id, see view client-hints-app/regexes/hints/categories.yml file
# 1: 'tools'
# ...
# 10: 'dating'
# 11: 'movies'

# ST = store in play market ( 0 no, 1 yes)
# TP = type app,  browser or app
# BD = bad app: scram or patched app (1 yes)

# Browsers
'acr.browser.Hexa': 'CT=1;NM=Hexa Web Browser;ST=0;TP=browser;'
'acr.browser.raisebrowserfull': 'CT=1;NM=Raise Fast Browser;ST=1;TP=browser;'
'acr.tez.browse': 'CT=1;NM=Browspeed Browser;ST=0;TP=browser;'
'com.Fast.BrowserUc.lite': 'CT=1;NM=Fast Browser UC Lite;ST=1;TP=browser;'
'acr.browser.barebones': 'CT=1;NM=Lightning Browser;ST=1;TP=browser;'
'anar.app.darkweb': 'CT=1;NM=Dark Web Browser;ST=1;TP=browser;'
'com.kiwibrowser.browser': 'CT=1;NM=Kiwi Browser;ST=1;TP=browser;'
'com.cloudmosa.puffinFree': 'CT=1;NM=Puffin Web Browser;ST=1;TP=browser;'
'com.aloha.browser': 'CT=1;NM=Aloha Browser;ST=1;TP=browser;'
'com.cake.browser': 'CT=1;NM=Cake Browser;ST=1;TP=browser;'
'com.UCMobile.intl': 'CT=1;NM=UC Browser;ST=1;TP=browser;'
'com.iebrowser.fast': 'CT=1;NM=IE Browser Fast;ST=1;TP=browser;'
'com.internet.browser.secure': 'CT=1;NM=Internet Browser Secure;ST=1;TP=browser;'
```
[Full list browser](https://github.com/sanchezzzhak/node-device-detector/tree/client-hints-app/regexes/hints)

[Full app list](https://github.com/sanchezzzhak/node-device-detector/blob/client-hints-app/regexes/hints/apps.yml)

test fixtures  (these are browsers that I personally found in my logs with headers)
```yml
---
-
  user_agent: Mozilla/5.0 (Linux; U; Android 8.1.0; ru-ru; ZC554KL Build/OPM1.171019.011) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/Mint Browser/3.9.1
  headers:
    X-Requested-With: com.mi.globalbrowser.mini
  os:
    name: Android
    version: 8.1.0
    platform: ''
  client:
    type: browser
    name: Mint Browser
    version: 3.9.1
    engine: WebKit
    engine_version: '537.36'
  device:
    type: smartphone
    brand: Asus
    model: ZenFone 4 Max
  os_family: Android
  browser_family: Chrome

-
  user_agent: Mozilla/5.0 (Linux; Android 8.1.0; ZC554KL Build/OPM1.171019.011;) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36
  headers:
    X-Requested-With: mark.via.gp
  os:
    name: Android
    version: "8.1.0"
    platform: ""
  client:
    type: browser
    name: Via
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: Asus
    model: ZenFone 4 Max
  os_family: Android
  browser_family: Chrome

-
  user_agent: Mozilla/5.0 (Linux; Android 8.1.0; Nomi_C080034 Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 Mobile Safari/537.36
  headers:
    X-Requested-With: com.pure.mini.browser
  os:
    name: Android
    version: "8.1.0"
    platform: ""
  client:
    type: browser
    name: Pure Mini Browser
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: tablet
    brand: Nomi
    model: Libra 4 LTE
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 10; SM-A115F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.115 Mobile Safari/537.36
  headers:
    X-Requested-With: acr.browser.raisebrowserfull
  os:
    name: Android
    version: "10"
    platform: ""
  client:
    type: browser
    name: Raise Fast Browser
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: Samsung
    model: Galaxy A11
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 7.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/1.0 Chrome/59.0.3029.83 Mobile Safari/537.36
  headers:
    X-Requested-With: com.Fast.BrowserUc.lite
  os:
    name: Android
    version: "7.0"
    platform: ""
  client:
    type: browser
    name: Fast Browser UC Lite
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: ""
    model: ""
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 10; DRA-LX9 Build/HUAWEIDRA-LX9; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.93 Mobile Safari/537.36
  headers:
    X-Requested-With: acr.browser.barebones
  os:
    name: Android
    version: "10"
    platform: ""
  client:
    type: browser
    name: Lightning Browser
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: Huawei
    model: Y5p
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 10; CPH2179 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36
  headers:
    X-Requested-With: anar.app.darkweb
  os:
    name: Android
    version: "10"
    platform: ""
  client:
    type: browser
    name: Dark Web Browser
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: OPPO
    model: A15s
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 10; Infinix X682B Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36
  headers:
    X-Requested-With: com.kiwibrowser.browser
  os:
    name: Android
    version: "10"
    platform: ""
  client:
    type: browser
    name: Kiwi Browser
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: Infinix
    model: Hot 10
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 10; SM-A013F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36
  headers:
    X-Requested-With: com.cloudmosa.puffinFree
  os:
    name: Android
    version: "10"
    platform: ""
  client:
    type: browser
    name: Puffin Web Browser
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: Samsung
    model: Galaxy A01 Core
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 7.0; Mobicel_R1 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.116 Mobile Safari/537.36
  headers:
    X-Requested-With: com.aloha.browser
  os:
    name: Android
    version: "7.0"
    platform: ""
  client:
    type: browser
    name: Aloha Browser
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: smartphone
    brand: Mobicel
    model: R1
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 11; Redmi Note 9S Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36
  headers:
    X-Requested-With: com.cake.browser
  os:
    name: Android
    version: "11"
    platform: ""
  client:
    type: browser
    name: Cake Browser
    version: ""
    engine: Blink
    engine_version: ""
  device:
    type: phablet
    brand: Xiaomi
    model: Redmi Note 9S
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; U; Android 8.1.0; en-US; Lenovo L18021 Build/O11019) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.91 UCBrowser/11.4.8.1012 Mobile Safari/537.36
  headers:
    X-Requested-With: com.UCMobile.intl
  os:
    name: Android
    version: 8.1.0
    platform: ''
  client:
    type: browser
    name: UC Browser
    version: '11.4.8.1012'
    engine: WebKit
    engine_version: '537.36'
  device:
    type: smartphone
    brand: Lenovo
    model: A3
  os_family: Android
  browser_family: ''
-
  user_agent: Mozilla/5.0 (Linux; Android 9; ZTE Blade V10 Vita Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Mobile Safari/537.36
  headers:
    X-Requested-With: com.UCMobile.intl
  os:
    name: Android
    version: '9'
    platform: ''
  client:
    type: browser
    name: UC Browser
    version: ''
    engine: Blink
    engine_version: ''
  device:
    type: smartphone
    brand: ZTE
    model: Blade V10 Vita
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 8.1.0; Neffos_C9A Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36
  headers:
    X-Requested-With: com.iebrowser.fast
  os:
    name: Android
    version: 8.1.0
    platform: ''
  client:
    type: browser
    name: IE Browser Fast
    version: ''
    engine: Blink
    engine_version: ''
  device:
    type: smartphone
    brand: Neffos
    model: C9A
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 11; M2004J19C Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile Safari/537.36
  headers:
    X-Requested-With: com.iebrowser.fast
  os:
    name: Android
    version: '11'
    platform: ''
  client:
    type: browser
    name: IE Browser Fast
    version: ''
    engine: Blink
    engine_version: ''
  device:
    type: smartphone
    brand: Xiaomi
    model: Redmi 9
  os_family: Android
  browser_family: Chrome
-
  user_agent: Mozilla/5.0 (Linux; Android 11; Pixel 3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Mobile Safari/537.36
  headers:
    X-Requested-With: org.telegram.messenger
  os:
    name: Android
    version: '11'
    platform: ''
  client:
    type: mobile app
    name: Telegram
    version: ''
  device:
    type: smartphone
    brand: Google
    model: Pixel 3
  os_family: Android
-
  user_agent: Mozilla/5.0 (Linux; Android 10; M2006C3LG Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36Snapchat11.59.0.35 (M2006C3LG; Android 10#V12.0.17.0.QCDMIXM#29; gzip)
  headers:
    X-Requested-With: com.snapchat.android
  os:
    name: Android
    version: '10'
    platform: ''
  client:
    type: mobile app
    name: Snapchat
    version: ''
  device:
    type: smartphone
    brand: Xiaomi
    model: Redmi 9A
  os_family: Android
```
