### ISSUE TITLE
Device not detect for realme C25Y and Wiko Y62

### ISSUE THREAD

**Issue by amancini** [matomo-org/device-detector#7096]
Hello,

first, thank you for your work.

for this user agents the device are not extracted:

dalvik/2.1.0 (linux; u; android 11; w-k610-fra build/rp1a.200720.011)  --> Wiko Y62
mozilla/5.0 (linux; android 11; rmx3269) applewebkit/537.36 (khtml, like gecko) chrome/100.0.4896.88 mobile safari/537.36 --> realme C25Y

Best regards

**Comment by sanchezzzhak** [comment]
Hi.
In the 6th version of matomo-org/device-detector these devices were detected.

```yml
user_agent: dalvik/2.1.0 (linux; u; android 11; w-k610-fra build/rp1a.200720.011)
os:
  name: Android
  version: "11"
  platform: ""
client:
  type: browser
  name: Android Browser
  version: ""
  engine: WebKit
  engine_version: ""
device:
  type: smartphone
  brand: Wiko
  model: Y62
os_family: Android
browser_family: Android Browser
```
```yml
user_agent: mozilla/5.0 (linux; android 11; rmx3269) applewebkit/537.36 (khtml, like gecko) chrome/100.0.4896.88 mobile safari/537.36
os:
  name: Android
  version: "11"
  platform: ""
client:
  type: browser
  name: Chrome Mobile
  version: 100.0.4896.88
  engine: Blink
  engine_version: 100.0.4896.88
device:
  type: smartphone
  brand: Realme
  model: C25Y
os_family: Android
browser_family: Chrome
```
