### ISSUE TITLE
User-Agent for Container-related tools

### ISSUE THREAD

**Issue by josegomezr** [matomo-org/device-detector#7194]
Hi there,

I'd like to contribute some new regexes to detect container runtimes (docker, buildah, and friends).

My journey started on plausible/analytics#2078, then hopped to elixir-inspector/ua_inspector#29 and I was pointed here!

How can I contribute the new regexes?

I got potential regexes ([here](https://github.com/plausible/analytics/pull/2078/files#diff-c40acb1a72fded5eb0d750d363c9bb5bfb62689566b3c513324d56971f858f50)) & samples below:

**Container Runtimes & Tools**:
* containers: `containers/5.17.0 (github.com/containers/image)`
* containerd: `containerd/v1.4.13-k3s1` & `containerd/1.5.11+azure-1`
* docker: `docker/20.10.12 go/go1.16.12 git-commit/459d0df kernel/3.10.0-1160.49.1.el7.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.12 \(linux\))`
* cri-o: `cri-o/1.16.1 go/go1.12.17 os/linux arch/amd64`
* artifactory: `Artifactory/7.21.5 72105900`
* gcr: `go-containerregistry/v0.11.0`
* buildah: `Buildah/1.23.1`
* buildkit: `buildkit/v0.10`
* Open Build Service: `BSRPC 0.9.1`
* skopeo: `skopeo/1.7.0`

**Down here there's no potential regex yet:**

* helm: `Helm/3.9.2`
* harbor-registry-client: `harbor-registry-client`

**Bots**
* renovatebot: `RenovateBot/32.99.9`

**Libraries**
* ruby-rest-client: `rest-client/2.1.0 (linux x86_64) ruby/2.7.6p219`

All user agents were taken out logs from of a production container registry.

**Comment by sanchezzzhak** [comment]
Hi
You have two ways: provide a list of user agents and wait for someone to make PR to this issue or  do make PR self.

How to make PR self:
* Fork reporitory
* `git clone <url_fork>
* `cd device-detector`
* next install dependencies with composer  (it is a package manager in the PHP world  https://getcomposer.org/doc/00-intro.md)
* `php composer.phar install`      

Add new regex to regexes/libraries.yml 

```yml
- regex: 'Artifactory/([.\d]+)'
  name: 'Artifactory'
  version: '$1'
```

create test to Tests/Client/fixtures/library.yml
you can use the command `php mics/test.php "Artifactory/7.21.5 72105900"`

```yml
user_agent: Artifactory/7.21.5 72105900
os: [ ]
client:
  type: library
  name: Artifactory
  version: 7.21.5
device:
  type: ""
  brand: ""
  model: ""
os_family: Unknown
browser_family: Unknown
```
remove unnecessary parameters from the result (for example, this example should look like this)
```yml 
-
user_agent: Artifactory/7.21.5 72105900
client:
  type: library
  name: Artifactory
  version: 7.21.5
```


you can test yourself at any time, with the help of tests

in console run tests
```
/usr/bin/php /srv/www/device-detector/vendor/phpunit/phpunit/phpunit --configuration /srv/www/device-detector/phpunit.xml.dist /srv/www/device-detector/Tests
```
if you have a PHPstorm, you can run the tests like this.
![image](https://user-images.githubusercontent.com/1337066/182662512-d19fe4ea-ac86-4303-a634-3c2ded44c13e.png)

Next, make a commit.
Go to your fork page, GitHub will offer to send a PR.
