### ISSUE TITLE
ClientHints plan upgrade

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#7274]
https://www.chromium.org/updates/ua-reduction/#proposed-rollout-plan

according to this information, the user-agent will be depersonalized at maximum for browsers: Chromium, Opera, YandexBrowser, Brave etc

we will need to adjust all regular expressions and abandon the pattern
`BrandName ([^;)]+)(?: Build|[;)])` or set like this `BrandName ([^;)]+)(?: Build|[;)]|$)`

more details https://51degrees.com/blog/countdown-to-gday-phase-5-reduced-desktop-ua

**Comment by zhouhui** [comment]
Hi @sanchezzzhak, I have a question about reduced user-agent:  Is it possible to detect device-type( mobile, tablet, desktop, etc.) in reduced user agent only without client-hints? Thanks!

**Comment by sanchezzzhak** [comment]
Hi, yes it will still be possible

**Comment by zhouhui** [comment]
> Hi, yes it will still be possible

Thanks for your quick reply. From the file 'mobiles.yml', I see some devices types are detected in model regex, for an example:
```
Microsoft:
  regex: 'KIN\.(One|Two)|RM-(?:1010|1031|106[57]|107[23467]|1089|109[02]|1096|1099|1109|111[348]|1127|1141|115[24]|994)|Microsoft; Lumia|Lumia (?:1530|1320|950|850|650|640|550|535|435)|Corporation/Surface|Surface Duo|Surface 3'
  device: 'smartphone'
  models:
    - regex: 'Surface Duo 2'
      device: 'tablet'
      model: 'Surface Duo 2'
```

And from the google ua-reduction doc, the part of Model would be reduced in user agent, so I guess, for the target devices of 'Surface Duo 2', the device-type would be detected as 'smartphone' instead of the accurate result 'tablet' with only reduced ua (without client-hints). Am I correct? If so, do we have other ways to get the accurate device-type?  Thanks a lot.
