### ISSUE TITLE
Device not detected

### ISSUE THREAD

**Issue by z0mb1ek** [matomo-org/device-detector#7321]
ua: Mozilla/5.0 (Linux; U; Android 12; RMX3363 Build/RKQ1.210503.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.44 Mobile Safari/537.36 OPR/66.2.2254.64268

This is:
```
type: "smartphone"
brand: "realme"
brand_code: "realme"
brand_url: "https://www.realme.com/"
name: "GT Master Edition (5G)"
```

**Comment by liviuconcioiu** [comment]
This device is already detected:

```YAML
-
  user_agent: Mozilla/5.0 (Linux; U; Android 12; RMX3363 Build/RKQ1.210503.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.44 Mobile Safari/537.36 OPR/66.2.2254.64268
  os:
    name: Android
    version: "12"
    platform: ""
  client:
    type: browser
    name: Opera Mobile
    version: 66.2.2254.64268
    engine: Blink
    engine_version: 109.0.5414.44
  device:
    type: smartphone
    brand: Realme
    model: GT Master Edition
  os_family: Android
  browser_family: Opera
```

If you use Matomo, you have to wait until the updates are pushed there.
