### ISSUE TITLE
Improvements to version and engine version detection

### ISSUE THREAD

**Issue by liviuconcioiu** [matomo-org/device-detector#7405]
The current detection should be improved for engine and engine version detection.

**version: 23.3.4.81
engine_version: 110.0.5481.208**

```
user_agent: Mozilla/5.0 (Linux; arm_64; Android 13; SM-A715F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 YaBrowser/23.3.4.81.00 SA/3 Mobile Safari/537.36
headers:
    Sec-CH-UA: "Chromium";v="110.0.5481.208", "Not A(Brand";v="24.0.0.0", "YaBrowser";v="23.3.4.81"
    Sec-CH-UA-Platform: Android
    Sec-CH-UA-Mobile: ?1
    Sec-CH-UA-Full-Version: 23.3.4.81
    Sec-CH-UA-Platform-Version: 13.0.0
    Sec-CH-UA-Model: SM-A715F
    Sec-CH-Prefers-Color-Scheme: light
os:
    name: Android
    version: 13.0.0
    platform: ARM
client:
    type: browser
    name: Yandex Browser
    version: 23.3.4.81.00
    engine: Blink
    engine_version: 110.0.0.0
device:
    type: smartphone
    brand: Samsung
    model: Galaxy A71
os_family: Android
browser_family: Unknown
```

**version: 109.0.5414.61
engine_version: 109.0.5414.61**

```
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
headers:
    Sec-CH-UA: "Chromium";v="109.0.5414.61", "Not_A Brand";v="99.0.0.0"
    Sec-CH-UA-Platform: Windows
    Sec-CH-UA-Mobile: ?0
    Sec-CH-UA-Full-Version: 109.0.5414.61
    Sec-CH-UA-Platform-Version: 14.0.0
    Sec-CH-UA-Arch: x86
    Sec-CH-UA-Bitness: "64"
    Sec-CH-Prefers-Color-Scheme: light
os:
    name: Windows
    version: "11"
    platform: x64
client:
    type: browser
    name: Chrome
    version: 109.0.0.0
    engine: Blink
    engine_version: 109.0.0.0
device:
    type: desktop
    brand: ""
    model: ""
os_family: Windows
browser_family: Chrome
```

**version: 107.0.5304.74
engine_version: 107.0.5304.74**

```
user_agent: Mozilla/5.0 (Linux; Android 12; moto g82 5G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36
headers:
    Sec-CH-UA: "Chromium";v="107.0.5304.74", "Not=A?Brand";v="24.0.0.0"
    Sec-CH-UA-Platform: Android
    Sec-CH-UA-Mobile: ?1
    Sec-CH-UA-Full-Version: 107.0.5304.74
    Sec-CH-UA-Platform-Version: 12.0.0
    Sec-CH-UA-Model: moto g82 5G
    Sec-CH-Prefers-Color-Scheme: light
os:
    name: Android
    version: 12.0.0
    platform: ""
client:
    type: browser
    name: Chrome Mobile
    version: 107.0.0.0
    engine: Blink
    engine_version: 107.0.0.0
device:
    type: smartphone
    brand: Motorola
    model: Moto G82 5G
os_family: Android
browser_family: Chrome
```

**version: 106.0.5400.0
engine_version: 106.0.5400.0**

```
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Iron Safari/537.36
headers:
    Sec-CH-UA: "Not;A=Brand";v="99.0.0.0", "Chromium";v="106.0.5400.0"
    Sec-CH-UA-Platform: Windows
    Sec-CH-UA-Mobile: ?0
    Sec-CH-UA-Full-Version: 106.0.5400.0
    Sec-CH-UA-Platform-Version: 0.3.0
    Sec-CH-UA-Arch: x86
    Sec-CH-UA-Bitness: "64"
    Sec-CH-Prefers-Color-Scheme: light
os:
    name: Windows
    version: "10"
    platform: x64
client:
    type: browser
    name: Iron
    version: 106.0.0.0
    engine: Blink
    engine_version: 106.0.0.0
device:
    type: desktop
    brand: ""
    model: ""
os_family: Windows
browser_family: Chrome
```
