### ISSUE TITLE
Method to detect headless/automation

### ISSUE THREAD

**Issue by AndiLeni** [matomo-org/device-detector#7441]
Hello,

is there any method to check whether a request is coming from a headless browser or is automated?

Thanks and kind regards

**Comment by sanchezzzhak** [comment]
Hola, you mean `headless chrome` https://developer.chrome.com/blog/headless-chrome/?

**Comment by AndiLeni** [comment]
@sanchezzzhak yes, f.e.
Or headless firefox, puppeteer and other automated accesses.

**Comment by sanchezzzhak** [comment]
If the data is like this, then yes we define it.

input
```yml
  user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5672.63 Safari/537.36
  headers:
    Sec-CH-UA: '"HeadlessChrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"'
    Sec-CH-UA-Platform: 'Linux'
    Sec-CH-UA-Mobile: '?0'
```    
result 
```yml
client:
    type: browser
    name: Headless Chrome
    version: 113.0
    engine: Blink
    engine_version: 113.0.5672.63
    family: Chrome
```
input
```yml
  user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/113.0.5672.63 Safari/537.36
  headers:
    Sec-CH-UA: '"HeadlessChrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"'
    Sec-CH-UA-Platform: 'Linux'
    Sec-CH-UA-Mobile: '?0'
```
result 
```yml
client:
    type: browser
    name: Headless Chrome
    version: 113.0.5672.63
    engine: Blink
    engine_version: 113.0.5672.63
    family: Chrome
```

this is if you don't play with the settings.

example

```js
const puppeteer = require('puppeteer');

(async () => {
        const browser = await puppeteer.launch({ headless: false });
        console.log(await browser.userAgent());
        await browser.close();
})();
```

result default ua `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.0 Safari/537.36` and this is normal.

to protect against content theft, you should not rely on UA and headers.
To protect yourself from bots, you can use the cloudfare or make a similar product.

<noindex>
is first visit site then show page for js check behavior  mouse
--- check position mouse x and y !== 0 for timeout then redirect 403
--- check click button or page and check event.isTrusted !== true then redirect 403
--- check all accept right and  save token and redirect to saved url earlier.

(the behavior of the mouse can also be deceived if drivers are connected to control this device. (but this is small who uses))
</noindex>
