### ISSUE TITLE
Various Devices Detection Improvement

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7528]
### Next
https://www.next.com.tr/4k-android-tv-box-iptv-uydu-alicisi
Device: tv (Not sure), Brand: Next

- [x] NEXT 2000-HD PLUS_VLC/3.0.14 LibVLC/3.0.14
https://www.next.com.tr/2000-hd-plus
```yml
user_agent: NEXT 2000-HD PLUS_VLC/3.0.14 LibVLC/3.0.14
os: [ ]
client:
  type: mediaplayer
  name: VLC
  version: 3.0.14
device:
  type: tv
  brand: 'Next & NextStar'
  model: 2000 HD Plus
os_family: Unknown
browser_family: Unknown
```

- [x] NEXT 2000 WiFi_VLC/3.0.14 LibVLC/3.0.14
https://www.next.com.tr/2000-wi-fi
```yml
user_agent: NEXT 2000 WiFi_VLC/3.0.14 LibVLC/3.0.14
os: [ ]
client:
  type: mediaplayer
  name: VLC
  version: 3.0.14
device:
  type: tv
  brand: 'Next & NextStar'
  model: 2000 WiFi
os_family: Unknown
browser_family: Unknown
```

- [x] NEXT 2071_VLC/3.0.14 LibVLC/3.0.14
https://www.next.com.tr/2071
```yml
user_agent: NEXT 2071_VLC/3.0.14 LibVLC/3.0.14
os: [ ]
client:
  type: mediaplayer
  name: VLC
  version: 3.0.14
device:
  type: tv
  brand: 'Next & NextStar'
  model: "2071"
os_family: Unknown
browser_family: Unknown
```

### Vidaa OS Devices
- [x] Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.140 Safari/537.36 OPR/46.0.2207.0 OMI/4.21.4.112.Catcher4.69 Model/Hisense-MT9602 VIDAA/5.0(QILIVE;SmartTV;VS0332FC1;MTK9602/V0000.01.00Q.M0926;HD)
Brand: Qilive

```yml
user_agent: Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.140 Safari/537.36 OPR/46.0.2207.0 OMI/4.21.4.112.Catcher4.69 Model/Hisense-MT9602 VIDAA/5.0(QILIVE;SmartTV;VS0332FC1;MTK9602/V0000.01.00Q.M0926;HD)
os:
  name: VIDAA
  version: "5.0"
  platform: ARM
client:
  type: browser
  name: Opera Devices
  version: 4.21.4.112
  engine: Blink
  engine_version: 84.0.4147.140
device:
  type: tv
  brand: Qilive
  model: Smart TV
os_family: GNU/Linux
browser_family: Opera
```

- [x] Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.140 Safari/537.36 OPR/46.0.2207.0 OMI/4.21.4.112.Catcher4.69 Model/Hisense-MT9602 VIDAA/5.0(JVC-CVTE;SmartTV;VS0432FD1;MTK9602/V0000.01.00R.N0302;HD)
Brand: JVC
```yml
user_agent: Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.140 Safari/537.36 OPR/46.0.2207.0 OMI/4.21.4.112.Catcher4.69 Model/Hisense-MT9602 VIDAA/5.0(JVC-CVTE;SmartTV;VS0432FD1;MTK9602/V0000.01.00R.N0302;HD)
os:
  name: VIDAA
  version: "5.0"
  platform: ARM
client:
  type: browser
  name: Opera Devices
  version: 4.21.4.112
  engine: Blink
  engine_version: 84.0.4147.140
device:
  type: tv
  brand: JVC
  model: Smart TV
os_family: GNU/Linux
browser_family: Opera

```

### Xiaomi Mi TV
- [x] Dalvik/2.1.0 (Linux; U; Android 11; MiTV-MOOR4 Build/RTM5.220609.003)
Device: tv
```yml
user_agent: Dalvik/2.1.0 (Linux; U; Android 11; MiTV-MOOR4 Build/RTM5.220609.003)
os:
  name: Android
  version: "11"
  platform: ""
client:
  type: browser
  name: Android Browser
  version: ""
  engine: WebKit
  engine_version: ""
device:
  type: tv
  brand: Xiaomi
  model: MiTV A Pro
os_family: Android
browser_family: Android Browser
```

### Others
- [x] Mozilla/5.0 (Linux;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 SRAF/4.0 (; SERAPHIC; SERAPHIC; v4.0; v1.0; ); CE-HTML/1.0 hbbtv NETRANGEMMH
Device: tv
```yml
user_agent: Mozilla/5.0 (Linux;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 SRAF/4.0 (; SERAPHIC; SERAPHIC; v4.0; v1.0; ); CE-HTML/1.0 hbbtv NETRANGEMMH
os:
  name: GNU/Linux
  version: ""
  platform: ""
client:
  type: browser
  name: Seraphic Sraf
  version: "4.0"
  engine: Blink
  engine_version: 47.0.2526.106
device:
  type: tv
  brand: ""
  model: ""
os_family: GNU/Linux
browser_family: Chrome
```

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.150 Model/Vestel-MB230 VSTVB MB200 HbbTV/1.5.1 (+DRM; CONTINENTAL_EDI; MB230; 0.51.30.0; ; _TV_NT72671_2019;) SmartTvA/3.0.0
Brand: Continental Edison (https://www.amazon.de/-/en/Continental-Edison-Smart-1366-728/dp/B0841MMT16)

```yml
user_agent: Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.150 Model/Vestel-MB230 VSTVB MB200 HbbTV/1.5.1 (+DRM; CONTINENTAL_EDI; MB230; 0.51.30.0; ; _TV_NT72671_2019;) SmartTvA/3.0.0
os:
  name: GNU/Linux
  version: ""
  platform: ""
client:
  type: browser
  name: Opera Devices
  version: 4.13.5.431
  engine: Blink
  engine_version: 67.0.3396.99
device:
  type: tv
  brand: Continental Edison
  model: Smart TV (2019)
os_family: GNU/Linux
browser_family: Opera
```

- [x] Dalvik/2.1.0 (Linux; U; Android 5.1.1; Brandt Android TV 638 Build/LMY47V)
Brand: Brandt (https://brandt.dz/tv-android)

```yml
user_agent: Dalvik/2.1.0 (Linux; U; Android 5.1.1; Brandt Android TV 638 Build/LMY47V)
os:
  name: Android TV
  version: 5.1.1
  platform: ""
client:
  type: browser
  name: Android Browser
  version: ""
  engine: WebKit
  engine_version: ""
device:
  type: tv
  brand: Brandt
  model: ""
os_family: Android
browser_family: Android Browser
```

- [x] Dalvik/2.1.0 (Linux; U; Android 9; UnionTV Build/PPR2.180905.006.A1)
Device: tv, Brand: TCL (not sure)

```yml
user_agent: Dalvik/2.1.0 (Linux; U; Android 9; UnionTV Build/PPR2.180905.006.A1)
os:
  name: Android
  version: "9"
  platform: ""
client:
  type: browser
  name: Android Browser
  version: ""
  engine: WebKit
  engine_version: ""
device:
  type: tv
  brand: TCL
  model: UnionTV
os_family: Android
browser_family: Android Browser

```

- [x] Kodi/20.2 (Linux; Android 7.1.2; H96 PRO+ Build/NHG47L) Android/7.1.2 Sys_CPU/aarch64 App_Bitness/64 Version/20.2-(20.2.0)-Git:20230629-5f418d0b13
Device: tv (https://www.techpunt.nl/en/h96-pro-plus-3gb-32gb-tv-box-android-71.html)
```yml
user_agent: Kodi/20.2 (Linux; Android 7.1.2; H96 PRO+ Build/NHG47L) Android/7.1.2 Sys_CPU/aarch64 App_Bitness/64 Version/20.2-(20.2.0)-Git:20230629-5f418d0b13
os:
  name: Android
  version: 7.1.2
  platform: ARM
client:
  type: mediaplayer
  name: Kodi
  version: "20.2"
device:
  type: tv
  brand: H96
  model: Pro+
os_family: Android
browser_family: Unknown
```

- [x] Mozilla/5.0 (Linux; Android 8.0.0; Sagemcom DIW387_UHD_OOR Build/21.4.60) IPTV/6.1.11
Device: tv (https://www.youtube.com/watch?v=6q815yOHM-s)
```yml
user_agent: Mozilla/5.0 (Linux; Android 8.0.0; Sagemcom DIW387_UHD_OOR Build/21.4.60) IPTV/6.1.11
os:
  name: Android
  version: 8.0.0
  platform: ""
client:
  type: mobile app
  name: IPTV
  version: 6.1.11
device:
  type: tv
  brand: Ooredoo
  model: TV Box
os_family: Android
browser_family: Unknown

```

- [x] TiviMate/4.7.0 (Onn. 4K Streaming Box; Android 12)
Device: tv
```
user_agent: TiviMate/4.7.0 (Onn. 4K Streaming Box; Android 12)
os:
  name: Android
  version: "12"
  platform: ""
client:
  type: mobile app
  name: TiviMate
  version: 4.7.0
device:
  type: tv
  brand: ONN
  model: 4K Streaming Box
os_family: Android
browser_family: Unknown
```
