### ISSUE TITLE
Platform ARM wrong detect

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#7729]
if ARM is present in the brand name, we specify the ARM platform

In the usual case, we leave this field empty.

```
-
  user_agent: Mozilla/5.0 (Linux; Android 13; Armor 22) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
  os:
    name: Android
    version: "13"
    platform: ARM
  client:
    type: browser
    name: Chrome Mobile
    version: 126.0.0.0
    engine: Blink
    engine_version: 126.0.0.0
  device:
    type: smartphone
    brand: Ulefone
    model: Armor 22
  os_family: Android
  browser_family: Chrome
 ```

**Comment by liviuconcioiu** [comment]
The same for

```
-
  user_agent: Mozilla/5.0 (Linux; Android 10; Armadillo Phone) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.81 Mobile Safari/537.36
  os:
    name: Armadillo OS
    short_name: ARM
    version: ""
    platform: ARM
    family: Android
```
