### ISSUE TITLE
Yandex browser for organization

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#7743]
* [x] Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.870 YaBrowser/24.1.3.870 (corp-ext) Yowser/2.5 Safari/537.36
* [x] Mozilla/5.0 (Linux 6.1.57; ; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.234 Not_A Brand/8 YaBrowser/24.1.3.845 YaBrowserCorp/120 Yowser/2.5 Safari/537.36
* [x] Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 YaBrowser/23.7.1.1217 (corp) Yowser/2.5 Safari/537.36
* name: Yandex Browser Corp

is it worth adding?

**Comment by liviuconcioiu** [comment]
Yes. Why not? Also, I want to ask you if we should improve the Yandex browsers detection.

**Yandex Start** (https://play.google.com/store/apps/details?id=ru.yandex.searchplugin) - `YaApp_Android` or `ru.yandex.searchplugin`
```yml
-
  user_agent: Mozilla/5.0 (Linux; arm; Android 10; SM-A115F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.324 YaApp_Android/24.19.1 YaSearchBrowser/24.19.1 BroPP/1.0 SA/3 Mobile Safari/537.36
  os:
    name: Android
    version: 10.0.0
    platform: ARM
  client:
    type: browser
    name: Yandex Browser
    version: 24.1.9.324
    engine: Blink
    engine_version: 120.0.6099.324
  device:
    type: smartphone
    brand: Samsung
    model: Galaxy A11
  os_family: Android
  browser_family: Unknown
  headers:
    Sec-CH-UA: '"Not_A Brand";v="8.0.0.0", "Chromium";v="120.0.6099.291", "Yandex";v="24.1.9.324"'
    Sec-CH-UA-Platform: Android
    Sec-CH-UA-Mobile: ?1
    Sec-CH-UA-Full-Version: 24.1.9.324
    Sec-CH-UA-Platform-Version: 10.0.0
    Sec-CH-UA-Model: SM-A115F
-
  user_agent: Mozilla/5.0 (Linux; Android 12; SM-A025F Build/SP1A.210812.016) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.99 Mobile Safari/537.36 YaApp_Android/10.51 YaSearchBrowser/10.51
  os:
    name: Android
    version: "12"
    platform: ""
  client:
    type: browser
    name: Chrome Webview
    version: "123"
    engine: ""
    engine_version: ""
  device:
    type: smartphone
    brand: Samsung
    model: Galaxy A02s
  os_family: Android
  browser_family: Chrome
  headers:
    Sec-CH-UA: "Android WebView";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
    Sec-CH-UA-Platform: Android
    Sec-CH-UA-Mobile: ?1
    http-x-requested-with: ru.yandex.searchplugin
```

**Yandex with Alice** (https://play.google.com/store/apps/details?id=com.yandex.searchapp) - `YaSearchBrowser`
```yml
-
  user_agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaSearchBrowser/24.10.0 Mobile Safari/537.36
  os:
    name: Android
    version: 10.0.0
    platform: ""
  client:
    type: browser
    name: Yandex Browser
    version: 24.10.0
    engine: Blink
    engine_version: 120.0.0.0
  device:
    type: smartphone
    brand: Huawei
    model: P40 Lite
  os_family: Android
  browser_family: Unknown
  headers:
    Sec-CH-UA: "Not_A Brand";v="8.0.0.0", "Chromium";v="120.0.6099.234", "YaSearchBrowser";v="24.1.5.390", "Yowser";v="2.5", "BroPP";v="1.0", "YaSearchApp";v="24.15"
    Sec-CH-UA-Platform: Android
    Sec-CH-UA-Mobile: ?1
    Sec-CH-UA-Full-Version: 24.1.5.390
    Sec-CH-UA-Platform-Version: 10.0.0
    Sec-CH-UA-Model: JNY-LX1
```

**Yandex Browser** (https://play.google.com/store/apps/details?id=com.yandex.browser) - `YaBrowser`
```yml
-
  user_agent: Mozilla/5.0 (Linux; arm_64; Android 13; SM-S901U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 YaBrowser/23.3.4.84.00 SA/3 Mobile Safari/537.36
  os:
    name: Android
    version: 13.0.0
    platform: ARM
  client:
    type: browser
    name: Yandex Browser
    version: 23.3.4.84.00
    engine: Blink
    engine_version: 110.0.0.0
  device:
    type: smartphone
    brand: Samsung
    model: Galaxy S22
  os_family: Android
  browser_family: Unknown
  headers:
    Sec-CH-UA: '"Chromium";v="110.0.5481.208", "Not A(Brand";v="24.0.0.0", "YaBrowser";v="23.3.4.84"'
    Sec-CH-UA-Platform: Android
    Sec-CH-UA-Mobile: ?1
    Sec-CH-UA-Full-Version: 23.3.4.84
    Sec-CH-UA-Platform-Version: 13.0.0
    Sec-CH-UA-Model: SM-S901U1
-
  user_agent: Mozilla/5.0 (Linux; arm_64; Android 14; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.99 YaBrowser/24.4.4.99.00 SA/3 Mobile Safari/537.36
  os:
    name: Android
    version: 14.0.0
    platform: ARM
  client:
    type: browser
    name: Yandex Browser
    version: 24.4.4.99.00
    engine: Blink
    engine_version: 122.0.6261.99
  device:
    type: smartphone
    brand: Samsung
    model: Galaxy S22
  os_family: Android
  browser_family: Unknown
  headers:
    Sec-CH-UA: '"Chromium";v="122.0.6261.139", "Not(A:Brand";v="24.0.0.0", "Yandex";v="24.4.4.99"'
    Sec-CH-UA-Platform: Android
    Sec-CH-UA-Mobile: ?1
    Sec-CH-UA-Full-Version: 24.4.4.99
    Sec-CH-UA-Platform-Version: 14.0.0
    Sec-CH-UA-Model: SM-S901B
```
