### ISSUE TITLE
$dd->getDeviceName() empty

### ISSUE THREAD

**Issue by jcerdan** [matomo-org/device-detector#7829]
Hello,

sometimes $dd->getDeviceName() returns an empty string.
DD detects it's not a bot, but device is empty.

What does that mean? Is it for real a human interaction?

I got the HTTP_USER_AGENT for one of those:

Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/21G93 [FBAN/FBIOS;FBAV/479.1.0.33.109;FBBV/637241220;FBDV/iPhone15,2;FBMD/iPhone;FBSN/iOS;FBSV/17.6.1;FBSS/3;FBID/phone;FBLC/es_ES;FBOP/5;FBRV/639094949;IABMV/1]

Looks like FB app running on an iPhone...

regards

**Comment by liviuconcioiu** [comment]
HI @jcerdan! This is indeed the Facebook app running on iPhone 14 Pro, and is a human interaction.

In this case, device should have been a `phablet`. I think you are running an outdated version of Matomo or device-detector. Detection is working as expected:

```YML
-
  user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/21G93 [FBAN/FBIOS;FBAV/479.1.0.33.109;FBBV/637241220;FBDV/iPhone15,2;FBMD/iPhone;FBSN/iOS;FBSV/17.6.1;FBSS/3;FBID/phone;FBLC/es_ES;FBOP/5;FBRV/639094949;IABMV/1]'
  os:
    name: iOS
    version: 17.6.1
    platform: ""
  client:
    type: mobile app
    name: Facebook
    version: 479.1.0.33.109
  device:
    type: phablet
    brand: Apple
    model: iPhone 14 Pro
  os_family: iOS
  browser_family: Unknown
```

**Comment by liviuconcioiu** [comment]
> I'm running version 6.4.0. I have tested the user agent there: https://devicedetector.lw1.at
> 
> How do you get the info for device=phablet?

There's a bug on the website (user agent is wrongly encoded), reported in https://github.com/Findus23/devicedetector.net/issues/4.

If you use the php code, detection works.

```PHP
<?php

include_once 'path/to/spyc/Spyc.php';
include_once 'path/to/device-detector/autoload.php';

use DeviceDetector\ClientHints;
use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\AbstractDeviceParser;

AbstractDeviceParser::setVersionTruncation(AbstractDeviceParser::VERSION_TRUNCATION_NONE);

$userAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/21G93 [FBAN/FBIOS;FBAV/479.1.0.33.109;FBBV/637241220;FBDV/iPhone15,2;FBMD/iPhone;FBSN/iOS;FBSV/17.6.1;FBSS/3;FBID/phone;FBLC/es_ES;FBOP/5;FBRV/639094949;IABMV/1]';

$result = DeviceDetector::getInfoFromUserAgent($userAgent);

echo Spyc::YAMLDump($result, 2, 0);
```

**Comment by jcerdan** [comment]
I have checked commits. Looks like iOS improvement detection has been added after 6.4.0 release.
I'll try to get package until last commit and see if that solves the problem.
Thanks @liviuconcioiu

**Comment by jcerdan** [comment]
Hi,
I have detected that ```$dd->getDevice()``` returns ```null``` if Client Hints are passed to DeviceDetector.

So this code returns a null value:

```
$clientHints = ClientHints::factory($_SERVER);
$dd = new DeviceDetector($userAgent, $clientHints);
$dd->discardBotInformation();
$dd->parse();
dump($dd->getDevice());
```

while the same without ClientHints return the correct device name.

Is that a bug?

**Comment by liviuconcioiu** [comment]
> Is that a bug?

Yes, it is a bug. It was introduced in https://github.com/matomo-org/device-detector/pull/7807.

@sanchezzzhak can you look again at the code when you have time?

```PHP
<?php

include_once 'path/to/spyc/Spyc.php';
include_once 'path/to/device-detector/autoload.php';

use DeviceDetector\ClientHints;
use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\AbstractDeviceParser;

AbstractDeviceParser::setVersionTruncation(AbstractDeviceParser::VERSION_TRUNCATION_NONE);

$userAgent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/21G93 [FBAN/FBIOS;FBAV/479.1.0.33.109;FBBV/637241220;FBDV/iPhone15,2;FBMD/iPhone;FBSN/iOS;FBSV/17.6.1;FBSS/3;FBID/phone;FBLC/es_ES;FBOP/5;FBRV/639094949;IABMV/1]';

$clientHints = ClientHints::factory([]);
$result = DeviceDetector::getInfoFromUserAgent($userAgent, $clientHints);

echo Spyc::YAMLDump($result, 2, 0);
```

This test should return

```YML
---
  user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/21G93 [FBAN/FBIOS;FBAV/479.1.0.33.109;FBBV/637241220;FBDV/iPhone15,2;FBMD/iPhone;FBSN/iOS;FBSV/17.6.1;FBSS/3;FBID/phone;FBLC/es_ES;FBOP/5;FBRV/639094949;IABMV/1]'
  os:
    name: iOS
    version: 17.6.1
    platform: ""
  client:
    type: mobile app
    name: Facebook
    version: 479.1.0.33.109
  device:
    type: phablet
    brand: Apple
    model: iPhone 14 Pro
  os_family: iOS
  browser_family: Unknown
```

and not

```YML
---
user_agent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/21G93 [FBAN/FBIOS;FBAV/479.1.0.33.109;FBBV/637241220;FBDV/iPhone15,2;FBMD/iPhone;FBSN/iOS;FBSV/17.6.1;FBSS/3;FBID/phone;FBLC/es_ES;FBOP/5;FBRV/639094949;IABMV/1]'
os:
  name: iOS
  version: 17.6.1
  platform: ""
client:
  type: mobile app
  name: Facebook
  version: 479.1.0.33.109
device:
  type: ""
  brand: Apple
  model: ""
os_family: iOS
browser_family: Unknown
```
