### ISSUE TITLE
Wolvic Browser its correct engine Gecko?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#7854]
Restore UA from Clienthints
```
Mozilla/5.0 (Linux; Android 10.0.0; A8110) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Mobile VR Wolvic/1.0
Mozilla/5.0 (Linux; Android 10.0.0; A8110) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Mobile VR Wolvic/0.9
Mozilla/5.0 (Linux; Android 10.0.0; A8110) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Mobile VR Wolvic/0.9
Mozilla/5.0 (Linux; Android 10.0.0; A8110) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Mozilla/5.0 (Linux; Android 10.0.0; A8110) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
```

Original UA 
```
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Mobile VR Wolvic/1.0
```
clienthints from JS
```yml
'hints':
  brands:
    - brand: Not-A.Brand
      version: '99'
    - brand: Chromium
      version: '124'
  fullVersionList:
    - brand: Not-A.Brand
      version: 99.0.0.0
    - brand: Chromium
      version: 124.0.6367.221
  mobile: '1'
  model: A8110
  platform: Android
  platformVersion: 10.0.0
  uaFullVersion: 124.0.6367.221
  wow64: '0'
```
