### ISSUE TITLE
Add detect LeafOS 

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#7862]
current parse result:

```
user_agent: Mozilla/5.0 (Linux; Android 14; LeafOS on ARM64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
os:
  name: Android
  version: "14"
  platform: ARM
os_family: Android
```

expected result
```
user_agent: Mozilla/5.0 (Linux; Android 14; LeafOS on ARM64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
os:
  name: LeafOS
  version: ""
  platform: ARM
os_family: Android
```

site https://leafos.org/

**Comment by sanchezzzhak** [comment]
```yml
original UA: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36
client hints:
  brands:
    - brand: Not/A)Brand
      version: '8'
    - brand: Chromium
      version: '126'
  fullVersionList:
    - brand: Not/A)Brand
      version: 8.0.0.0
    - brand: Chromium
      version: 126.0.6478.71
  mobile: '1'
  model: LeafOS on ARM64
  platform: Android
  platformVersion: 14.0.0
  uaFullVersion: 126.0.6478.71
  wow64: '0'
```
