### ISSUE TITLE
Singlebox browser

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#7897]
https://singlebox.app/en/

* [x] Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Singlebox/38.2.0 Chrome/116.0.5845.190 Electron/26.2.2 Safari/537.36

current detect 
```yml
user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Singlebox/38.2.0 Chrome/116.0.5845.190 Electron/26.2.2 Safari/537.36
os:
  name: Mac
  version: 10.15.7
  platform: ""
client:
  type: mobile app
  name: Singlebox
  version: 38.2.0
device:
  type: desktop
  brand: Apple
  model: ""
os_family: Mac
browser_family: Unknown
```
