### ISSUE TITLE
Skye browser wrong client type for MacOs

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#7898]
* [x] Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Skye/6.4.1 Chrome/96.0.4664.110 Electron/16.0.7 Safari/537.36

current detect
```
user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Skye/6.4.1 Chrome/96.0.4664.110 Electron/16.0.7 Safari/537.36
os:
  name: Mac
  version: 10.15.7
  platform: ""
client:
  type: mobile app
  name: Skye
  version: 6.4.1
device:
  type: desktop
  brand: Apple
  model: ""
os_family: Mac
browser_family: Unknown
```

for window
```
  user_agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Skye/6.6.4 Chrome/95.0.4638.54 Safari/537.36
  client:
    type: browser
    name: Skye
    version: 6.6.4
    engine: Blink
    engine_version: 95.0.4638.54
    family: Chrome
```
