### ISSUE TITLE
Duplicate regexes

### ISSUE THREAD

**Issue by jrfavre** [matomo-org/device-detector#7944]
Hello, 

In regexes/device/mobiles.yml
Regex pattern "T-i708D" in duplicated on line 20757 and 20760. 
So I would replace it with
```
Panacom:
  regex: 'T-i708D'
  device: 'tablet'
  model: 'T-i708D'
```

In regexes/oss.yml
Regex pattern "15/tclwebkit" is duplicated on line 783 and 785. The one on 785 will never be reached. 
We may replace it with 
```
    - regex: '15/tclwebkit'
      version: '4.0'
```
