### ISSUE TITLE
Incorrect Classification of Sonos Devices as Portable Media Players

### ISSUE THREAD

**Issue by Ryan-Dilworth** [matomo-org/device-detector#8022]
Hi Matomo Team,

We’ve noticed that certain Sonos devices are currently classified as Portable Media Players, but they should be categorized as Smart Speakers instead. Sonos devices are designed for stationary home use, support networked multi-room audio, and typically require AC power, making them not portable.

Based on the current YAML regex, Sonos devices such as the following are incorrectly categorized:

ZP120
ZPS33
PLAY:5
PLAY:3
ONE
BEAM
ARC
MOVE and ROAM  (Note: These two are actually portable, but most Sonos devices aren’t.)

For example, Linux UpnP/1.0 Sonos/82.-60160 (ZPS33)

UPnP (Universal Plug and Play) support suggests it is network-connected and can interact with other smart home systems.
ZP stands for "ZonePlayer," a term used by Sonos for their devices which aligns with home audio setups

Here are the regex's in the portable_media_player.yml
```yml
# Sonos (sonos.com)
SONOS:
  regex: '(?:Sonos/.+\((?:ZP.+)\)|Sonos;)'
  device: 'portable media player'
  models:
    - regex: '\((ZPS(?:[13569]|1[1-578]|2[03])|ZP90)\)'
      model: '$1'
    - regex: 'Sonos;Beam;'
      model: 'Beam'
    - regex: 'Sonos;Roam;'
      model: 'Roam'
    - regex: 'Sonos;Bookshelf;'
      model: 'Bookshelf'
    - regex: 'Sonos;Move;'
      model: 'Move'
    - regex: 'Sonos;Play(\d);'
      model: 'Play:$1'
    - regex: 'Sonos;One;'
      model: 'One'
    - regex: 'Sonos;OneSL'
      model: 'OneSL'
```
Would it be possible to update the regex rules to reflect these changes? Let me know if you need additional data or sample user-agents.
