### ISSUE TITLE
What are the URLs in the YAML files used for?

### ISSUE THREAD

**Issue by nandor23** [matomo-org/device-detector#8033]
Hello,

A few of the YAML files contain `url` fields, but they don’t seem to be included in the parsed result. 
Are the URLs used anywhere, or do they serve a specific purpose?

```yml
- regex: 'Akregator(?:/(\d+[.\d]+))?'
  name: 'Akregator'
  version: '$1'
  url: 'http://userbase.kde.org/Akregator'
```

Result:

![Image](https://github.com/user-attachments/assets/d086de62-8a74-4bab-9c49-55a581afa6ad)
