### ISSUE TITLE
isMobileApp detect browser in phone?

### ISSUE THREAD

**Issue by filisko** [matomo-org/device-detector#8047]
Hi,

Does isMobileApp detect that the browser origin is from a mobile app?

**Comment by liviuconcioiu** [comment]
Hi,

Not really. Most regexes are for mobile apps, but there are also desktop apps like:

```yaml
-
  user_agent: Microsoft Office/16.0 (Windows NT 10.0; Microsoft PowerPoint 16.0.10730; Pro)
  client:
    type: mobile app
    name: Microsoft Office PowerPoint
    version: 16.0.10730
```

So you should not rely on client type. You can use `isMobile`.
